name: Merge PR

on:
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    name: Build and test
    uses: ./.github/workflows/build-and-test.yml

  bump-version:
    name: Bump version
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - uses: actions/checkout@v7
        with:
          ref: main
      
      - name: Fetch current version
        id: fetch-current-version
        run: |
          echo "version=$(cat ./plugins/glean/.claude-plugin/plugin.json | jq .version)" >> $GITHUB_OUTPUT

      - uses: actions/checkout@v7
        with:
          ref: ${{ github.ref }}

      - name: Fetch incoming version
        id: fetch-incoming-version
        run: |
          echo "version=$(cat ./plugins/glean/.claude-plugin/plugin.json | jq .version)" >> $GITHUB_OUTPUT

      - name: Validate incoming version
        id: validate-incoming-version
        run: |
          
